# Generated by Django 4.2.7 on 2023-11-08 08:05

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ad_emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Admn_username')),
            ],
        ),
    ]
