# Generated by Django 4.2.7 on 2023-11-08 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entry_TIME')),
                ('exit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Exit_TIME')),
                ('duration', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Durationj')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql.employee')),
            ],
        ),
    ]
