# Generated by Django 4.2.7 on 2023-11-08 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0003_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql.employee')),
            ],
        ),
    ]
